{
  "name": "miri",
  "on": [
    "push": {
      "branches": [
        "trunk",
        "v*.x",
        "ci/*"
      ]
    },
    "pull_request": {
      "branches": [
        "trunk",
        "v*.x"
      ]
    }
  ],
  "jobs": {
    "miri": {
      "name": "MIRI",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v2",
          "name": "Checkout"
        },
        {
          "run": "rustup toolchain install nightly --component miri \n
rustup override set nightly \n
cargo miri setup",
          "name": "Install Rust nightly"
        },
        {
          "run": "cargo miri test",
          "name": "Default features"
        }
      ]
    }
  }
}
